# Created with WinGet Updater using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MikeFarah.yq
PackageVersion: 4.54.1
InstallerLocale: en-US
InstallerType: portable
Commands:
- yq
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/mikefarah/yq/releases/download/v4.54.1/yq_windows_386.exe
  InstallerSha256: DDB66D113DA67ED9F62728268E64BBD3C2A1E31D2ECFCDE0C95BA5926555A73E
  AppsAndFeaturesEntries:
  - DisplayName: yq (x86)
- Architecture: x64
  InstallerUrl: https://github.com/mikefarah/yq/releases/download/v4.54.1/yq_windows_amd64.exe
  InstallerSha256: B645F47EBB3A0D2FBAB52998550BBD0A1706F23B5CA5F5B48E638C580BB70928
- Architecture: x64
  InstallerUrl: https://github.com/mikefarah/yq/releases/download/v4.54.1/yq_windows_amd64.exe
  InstallerSha256: B645F47EBB3A0D2FBAB52998550BBD0A1706F23B5CA5F5B48E638C580BB70928
  AppsAndFeaturesEntries:
  - DisplayName: yq (ARM64)
ManifestType: installer
ManifestVersion: 1.12.0
