name: Update WinGet Packages

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *' # Scheduled to run daily at 03:00

jobs:
  update:
    name: Update package ${{ matrix.id }}
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - id: "libvips.libvips"
            repo: "libvips/build-win64-mxe"
            url: "https://github.com/libvips/build-win64-mxe/releases/download/v{VERSION}/vips-dev-w64-all-{VERSION}.zip"
          
    steps:
    - name: Update Packages
      uses: michidk/winget-updater@latest
      with:
        komac-version: "2.6.0"
        komac-token: ${{ secrets.KOMAC_TOKEN }}
        identifier: ${{ matrix.id }}
        repo: ${{ matrix.repo }}
        url: ${{ matrix.url }}

  # cleanup:
  #   name: Cleanup branches
  #   needs: update # Not necessarily needed as PRs don't get closed that quick but still nice to have it in order
  #   runs-on: ubuntu-24.04
  #   steps:
  #   - name: Run Komac
  #     uses: michidk/run-komac@latest
  #     with:
  #       komac-version: "2.6.0"
  #       args: 'cleanup --only-merged --token=${{ secrets.KOMAC_TOKEN }}'
